#ifndef _MBEDTLS_CONFIG_H
#define _MBEDTLS_CONFIG_H

#define MBEDTLS_SHA256_C
#define MBEDTLS_ENTROPY_SHA256_ACCUMULATOR

#define MBEDTLS_NO_PLATFORM_ENTROPY
#define MBEDTLS_ENTROPY_HARDWARE_ALT

#define MBEDTLS_CHACHAPOLY_C
#define MBEDTLS_CHACHA20_C
#define MBEDTLS_POLY1305_C

#define MBEDTLS_ECDH_C
#define MBEDTLS_ECP_DP_CURVE25519_ENABLED
#define MBEDTLS_ENTROPY_C
#define MBEDTLS_CTR_DRBG_C

#endif